version: '3.8'

services:
  postgresql-terraform:
    image: postgres:16
    container_name: postgresql-terraform
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api-terraform:
    build:
      context: .
    container_name: api-terraform
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresql-terraform:5432/todos_db
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgresql-terraform
    volumes:
      - /app/node_modules

volumes:
  pgdata: 